### PR TITLE
Add teacher edition event filter

### PR DESCRIPTION
**Pull request by dougmartin**
Also updates Docker setup (from initial Fargate setup work a month ago that wasn't committed)

### CODE REVIEW

**Comment by scytacki** [comment]
This approach worries me because it is putting report specific code in the log puller. The log puller was intended to be a generic way to access logs.
Additionally Trudi did want to eventually see the teachers usage of non teacher edition materials in this report as well, so we'd be probably revising this custom code soon.

It might be best to just go with this approach for now, but here are few other options:
- extend the queries supported by the log puller so these kind of filters can be added to main query. Then add a new field in the external report portal model so external reports can specify a query filter that gets added to the log puller query generated by the portal.
- let the log puller get a parameter (or parameters) that lets the user add filters to the returned events. Perhaps these could be a map between a field name and a string to find in the field (like what is done in the current code). We'd need to be careful with this since it isn't signed by the portal, so we need to make sure these user added filters can't be used to see more events than the original signed portal query.
- keep this logic in the teacher edition report, and have it use an stream based request to filter the events first before passing them off to the main processing code. This still means the teacher edition report needs to download a lot of data, but it gives it the most flexibility for figuring out which events to keep and which to throw out.

**Comment by scytacki** [comment]
Of the options the first one might be the best. It strikes a balance between efficiency, security, and flexibility. The query filter could be complex and we would not need to worry about security as much because these could only be setup by admins.  Perhaps the biggest downside is maintainability since now deploying an external report requires additional configuration that we need to remember to keep up-to-date.

**Comment by dougmartin** [comment]
@scytacki could you approve this PR so that I can update production today?

**Comment by scytacki** [comment]
So we decided stick with this option for now and come back to it. 

Here is the PT story for when we come back to it: https://www.pivotaltracker.com/story/show/169648231

**Pull request merged**
